org: kshitijkumar123
app: aws-python
service: aws-serverless-python-project
frameworkVersion: "3"

# TODO:
# MAKE THE FRONTEND!!!!
# Clean up and restructure code files + add failure catching points -- today
# Add authorization and endpoint restriction -- tbd today
# Customers make incidents and send emails to users to info they are subscribed to -- today
# add basic ticket management
# - watch video for simple use cases
# - just one organization with employees
# insight emails about ticket with quote
# push amplify, api for prod
# additional stuff --
# chatgpt integration??
# queues?
# delete old stacks

custom:
  tableName: "watch-me-users-table-${sls:stage}"
  incidentsTableName: "incidents-table-${sls:stage}"
  region: ${self:provider.region}

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev

  iam:
    role:
      statements:
        # S3 role: Currently, this allows all access to all s3 buckets
        - Effect: Allow
          Action: "s3:*"
          Resource: "*"
        # DynamoDB role
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::GetAtt: [IncidentsTable, Arn]
        - Effect: Allow
          Action:
            - "ses:SendEmail"
          Resource: "*"
  environment:
    USERS_TABLE: ${self:custom.tableName}
    REGION: ${self:provider.region}
    INCIDENTS_TABLE: "incidents-table-${sls:stage}"

functions:
  quotes:
    handler: handler.get_quotes
    events:
      - http:
          path: quotes
          method: get
          cors: true
  subscribe:
    handler: handler.subscribe_user
    events:
      - http:
          path: subscribeUser
          method: post
          cors: true
  updatePermissions:
    handler: handler.update_acl
    events:
      - http:
          path: updatePermissions
          method: post
          cors: true
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: sendEmail
          method: post
          authorizer:
            name: customAuthorizer
          cors: true
      - schedule: cron(0 13 * * ? *)
  getSubscribers:
    handler: handler.get_subscribers
    events:
      - http:
          path: getSubscribers
          method: get
          authorizer:
            name: customAuthorizer
          cors: true
  preSignUp:
    handler: handler.pre_sign_up
    events:
      - cognitoUserPool:
          pool: amplifyreactapp6a4fef01_userpool_6a4fef01-dev
          trigger: PostConfirmation
          existing: true
          forceDeploy: true

  # Incidents CRUD
  getIncidents:
    handler: handler.get_incidents
    events:
      - http:
          path: incident/{id}
          method: get
          authorizer:
            name: customAuthorizer
          cors: true
  getReporterIncidents:
    handler: handler.get_reporter_incidents
    events:
      - http:
          path: incident/reporter/{id}
          method: get
          authorizer:
            name: customAuthorizer
          cors: true
  createIncidents:
    handler: handler.create_incidents
    events:
      - http:
          path: incident
          method: post
          authorizer:
            name: customAuthorizer
          cors: true

  updateIncidents:
    handler: handler.update_incidents
    events:
      - http:
          path: incident/{id}
          method: patch
          authorizer:
            name: customAuthorizer
          cors: true

  deleteIncidents:
    handler: handler.delete_incidents
    events:
      - http:
          path: incident/{id}
          method: delete
          # authorizer:
          #   name: customAuthorizer
          cors: true

  customAuthorizer:
    handler: handler.authorization
resources:
  Resources:
    Unauthorized:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          "gatewayresponse.header.Access-Control-Allow-Origin": "'*'"
          "gatewayresponse.header.Access-Control-Allow-Headers": "'*'"
        ResponseType: "DEFAULT_4XX"
        RestApiId:
          Ref: "ApiGatewayRestApi"

    # TODO: check if needed
    PostsMessage:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: watch-me-posts-${self:provider.stage}
    PostsSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref PostsMessage
        Protocol: email
        Endpoint: kshitijkumar.atom@gmail.com
        DeliveryPolicy:
          healthyRetryPolicy:
            numRetries: 20
            minDelayTarget: 30
            maxDelayTarget: 600
            backoffFunction: exponential
    # S3Assets:
    #   Type: AWS::S3::Bucket
    #   Properties:
    #     BucketName: user-posts-dev-assets
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

    IncidentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: incidentId
            AttributeType: S
        KeySchema:
          - AttributeName: incidentId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.incidentsTableName}

    # AWS Cognito
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-user-pool
        # email creds. for login
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    # Client for web app access to Cognito
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-user-pool-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: False
